# Generated by Django 5.1.1 on 2024-09-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livrariaOnline', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='catergory',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date_publication',
        ),
        migrations.RemoveField(
            model_name='book',
            name='front_book',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='book',
            name='synopsis',
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
